ci: strip lineageos disguise
its causing compilation issues

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -134,11 +134,11 @@ jobs:
           # Basic optimizations
           echo "CONFIG_KALLSYMS=y" >> "$CONFIG_FILE"
 
-      - name: "🛠 Apply kernel patches"
-        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
-        run: |
-          curl -L -o lineage.patch "https://raw.githubusercontent.com/topnotchfreaks/kernel_patches/main/0001-fs-lineageos-disguise.patch"
-          patch -p1 < lineage.patch || echo "Warning: Some hunks failed"
+      # - name: "🛠 Apply kernel patches"
+      #  working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
+      #  run: |
+      #    curl -L -o lineage.patch "https://raw.githubusercontent.com/topnotchfreaks/kernel_patches/main/0001-fs-lineageos-disguise.patch"
+      #    patch -p1 < lineage.patch || echo "Warning: Some hunks failed"
 
       - name: "🔧 Setup KernelSU (KSU variant only)"
         if: matrix.variant == 'ksu'
